#!/usr/bin/env bash
#
# One-command local playtest loop with no testnet and no Privy.
#
#   scripts/dev-local.sh            # start anvil, deploy, run server + web
#   scripts/dev-local.sh --reset    # also wipe the local database first
#
# Requires: bun, foundry (anvil + forge + cast) on PATH.
# Opens nothing; visit http://localhost:5173, pick a dev identity, and play.
# Open a second browser (or a private window) for the second player.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="$ROOT/packages/contracts"
SERVER="$ROOT/packages/server"
WEB="$ROOT/packages/web"

ANVIL_PORT="${ANVIL_PORT:-8545}"
SERVER_PORT="${SERVER_PORT:-3001}"
WEB_PORT="${WEB_PORT:-5173}"
RPC_URL="http://127.0.0.1:${ANVIL_PORT}"

# Well-known Anvil accounts (public test keys; never use on a real network).
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
SERVER_KEY="0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
SERVER_ADDRESS="0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"

FORGE_FLAGS="${FORGE_FLAGS:-}"   # e.g. --offline on machines that cannot fetch solc

for tool in bun anvil forge cast; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: $tool is not on PATH" >&2
    exit 1
  fi
done

if [[ "${1:-}" == "--reset" ]]; then
  echo "• Removing local database"
  rm -f "$SERVER"/*.db "$SERVER"/*.sqlite "$SERVER"/data/*.db 2>/dev/null || true
fi

PIDS=()
cleanup() {
  echo
  echo "• Shutting down"
  for pid in "${PIDS[@]:-}"; do
    [[ -n "$pid" ]] && kill "$pid" 2>/dev/null || true
  done
}
trap cleanup EXIT INT TERM

echo "• Starting anvil on :$ANVIL_PORT"
anvil --port "$ANVIL_PORT" --silent &
PIDS+=($!)
for _ in $(seq 1 50); do
  if cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then break; fi
  sleep 0.2
done

echo "• Deploying MockUSDC + GameEscrow"
(
  cd "$CONTRACTS"
  SERVER_WALLET_ADDRESS="$SERVER_ADDRESS" forge script script/DeployLocal.s.sol:DeployLocalScript \
    --rpc-url "$RPC_URL" --broadcast --private-key "$DEPLOYER_KEY" $FORGE_FLAGS >/dev/null
)

DEPLOY_JSON="$CONTRACTS/deployments/local.json"
ESCROW=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$DEPLOY_JSON','utf8')).escrow)")
USDC=$(bun -e "console.log(JSON.parse(require('fs').readFileSync('$DEPLOY_JSON','utf8')).usdc)")
echo "  escrow: $ESCROW"
echo "  usdc:   $USDC"

echo "• Writing packages/server/.env.local and packages/web/.env.local"
cat > "$SERVER/.env.local" <<EOF
# Generated by scripts/dev-local.sh — local Anvil playtest, no Privy.
NODE_ENV=development
AUTH_MODE=dev
CHAIN_ID=31337
RPC_URL=$RPC_URL
GAME_ESCROW_CONTRACT_ADDRESS=$ESCROW
USDC_CONTRACT_ADDRESS=$USDC
SERVER_WALLET_PRIVATE_KEY=$SERVER_KEY
TURN_TIMEOUT_SECONDS=${TURN_TIMEOUT_SECONDS:-120}
SETTLEMENT_ENABLED=true
PORT=$SERVER_PORT
LOG_LEVEL=${LOG_LEVEL:-info}
CORS_ALLOWED_ORIGINS=http://localhost:$WEB_PORT,http://127.0.0.1:$WEB_PORT
EOF

cat > "$WEB/.env.local" <<EOF
# Generated by scripts/dev-local.sh — local Anvil playtest, no Privy.
VITE_API_URL=http://localhost:$SERVER_PORT
VITE_WS_URL=ws://localhost:$SERVER_PORT
VITE_AUTH_MODE=dev
VITE_CHAIN_ID=31337
VITE_RPC_URL=$RPC_URL
VITE_ESCROW_CONTRACT_ADDRESS=$ESCROW
VITE_USDC_CONTRACT_ADDRESS=$USDC
VITE_EXPLORER_URL=
EOF

echo "• Starting server on :$SERVER_PORT"
(cd "$SERVER" && bun run dev) &
PIDS+=($!)

echo "• Starting web on :$WEB_PORT"
(cd "$WEB" && bun run dev -- --port "$WEB_PORT" --host 127.0.0.1) &
PIDS+=($!)

sleep 2
cat <<EOF

  Ready.
    Web:    http://localhost:$WEB_PORT
    Server: http://localhost:$SERVER_PORT
    Anvil:  $RPC_URL  (chain 31337)

  Open two browsers, pick two different dev identities on the login
  screen, create a game in one and join it in the other. Press Ctrl-C to
  stop everything.

EOF

wait
